// Generated by bun run mobile:api:generate from packages/application-api-contract/src/account/mcp.ts. Do not edit.
import { z } from "zod/v4";

export const ToolFormatSchema = z.enum(["json", "summary"]);

export const DescriptiveEntitySchema = z
	.object({
		id: z.string().optional(),
		name: z.string().optional(),
		publicUrl: z.string().optional(),
		summary: z.string().optional(),
	})
	.passthrough();

export const DynamoiListArtistsInputSchema = z
	.object({
		artistId: z.string().uuid().optional(),
		cursor: z.string().optional(),
		format: ToolFormatSchema.optional(),
		limit: z.number().int().min(1).max(50).optional(),
	})
	.strict();

const DynamoiGetCurrentUserIntentSchema = z.enum([
	"account_overview",
	"artist_access_check",
	"organization_access_check",
	"platform_connection_check",
]);

export const DynamoiGetCurrentUserInputSchema = z
	.object({
		format: ToolFormatSchema.optional(),
		intent: DynamoiGetCurrentUserIntentSchema.default("account_overview"),
	})
	.strict();

export const DynamoiAccountOverviewDescriptiveDataSchema = z
	.object({
		artistCount: z.number().optional(),
		artists: z
			.object({
				count: z.number(),
				summaries: z.array(DescriptiveEntitySchema),
			})
			.optional(),
		organizationCount: z.number().optional(),
		recommendedNextActions: z.array(z.string()).optional(),
		state: z.object({}).passthrough().optional(),
		summary: z.string().optional(),
		user: z.object({ name: z.string().optional() }).optional(),
	})
	.passthrough();

export const DynamoiArtistListDescriptiveDataSchema = z
	.object({
		artists: z.array(DescriptiveEntitySchema).optional(),
		nextCursor: z.string().optional(),
		summary: z.string().optional(),
		totalCount: z.number().optional(),
	})
	.passthrough();
