// Generated by bun run mobile:api:generate. Do not edit.
import { z } from "zod";
export const CampaignFundingPreviewOutputSchema = z.fromJSONSchema({
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "asOf": {
      "type": "string",
      "format": "date-time",
      "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"
    },
    "availableBalanceMinor": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 9_007_199_254_740_991
        },
        {
          "type": "null"
        }
      ]
    },
    "consentCopy": {
      "type": "string"
    },
    "consentCopyHash": {
      "type": "string"
    },
    "consentVersion": {
      "type": "string"
    },
    "currency": {
      "type": "string",
      "enum": [
        "USD",
        "EUR",
        "GBP",
        "CAD",
        "AUD",
        "MXN",
        "BRL",
        "JPY",
        "AED",
        "CHF",
        "CLP",
        "COP",
        "CZK",
        "DKK",
        "EGP",
        "HKD",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "KRW",
        "KZT",
        "MYR",
        "NGN",
        "NOK",
        "NZD",
        "PEN",
        "PHP",
        "PKR",
        "PLN",
        "QAR",
        "RON",
        "SAR",
        "SEK",
        "SGD",
        "THB",
        "TRY",
        "TWD",
        "TZS",
        "VND",
        "ZAR",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BSD",
        "BWP",
        "BYN",
        "BZD",
        "CDF",
        "CRC",
        "CVE",
        "DJF",
        "DOP",
        "DZD",
        "ETB",
        "FJD",
        "FKP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HNL",
        "HTG",
        "IQD",
        "ISK",
        "JMD",
        "JOD",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KYD",
        "LAK",
        "LKR",
        "LRD",
        "LSL",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MUR",
        "MVR",
        "MWK",
        "MZN",
        "NAD",
        "NIO",
        "NPR",
        "PAB",
        "PGK",
        "PYG",
        "RSD",
        "RWF",
        "SBD",
        "SCR",
        "SHP",
        "SLE",
        "SOS",
        "SRD",
        "STD",
        "SZL",
        "TJS",
        "TOP",
        "TTD",
        "UAH",
        "UGX",
        "UYU",
        "UZS",
        "VUV",
        "WST",
        "XAF",
        "XCD",
        "XCG",
        "XOF",
        "XPF",
        "YER",
        "ZMW"
      ]
    },
    "currencyExponent": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3
    },
    "firstWindowCardMinor": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 9_007_199_254_740_991
        },
        {
          "type": "null"
        }
      ]
    },
    "firstWindowCardUpperBoundMinor": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9_007_199_254_740_991
    },
    "firstWindowCreditCoverageMinor": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 9_007_199_254_740_991
        },
        {
          "type": "null"
        }
      ]
    },
    "firstWindowMinor": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9_007_199_254_740_991
    },
    "fullFlightCardMinor": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 9_007_199_254_740_991
        },
        {
          "type": "null"
        }
      ]
    },
    "fullFlightCardUpperBoundMinor": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 9_007_199_254_740_991
        },
        {
          "type": "null"
        }
      ]
    },
    "fullFlightCreditCoverageMinor": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 9_007_199_254_740_991
        },
        {
          "type": "null"
        }
      ]
    },
    "fullFlightMinor": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 9_007_199_254_740_991
        },
        {
          "type": "null"
        }
      ]
    },
    "fundingDays": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "maximum": 9_007_199_254_740_991
    },
    "initialWindowCount": {
      "type": "integer",
      "minimum": 1,
      "maximum": 2
    },
    "nextExpiryAt": {
      "anyOf": [
        {
          "type": "string",
          "format": "date-time",
          "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"
        },
        {
          "type": "null"
        }
      ]
    },
    "status": {
      "type": "string",
      "enum": [
        "known",
        "unavailable"
      ]
    },
    "windows": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "budgetMinor": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9_007_199_254_740_991
          },
          "endsAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"
          },
          "startsAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"
          }
        },
        "required": [
          "budgetMinor",
          "endsAt",
          "startsAt"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "asOf",
    "availableBalanceMinor",
    "consentCopy",
    "consentCopyHash",
    "consentVersion",
    "currency",
    "currencyExponent",
    "firstWindowCardMinor",
    "firstWindowCardUpperBoundMinor",
    "firstWindowCreditCoverageMinor",
    "firstWindowMinor",
    "fullFlightCardMinor",
    "fullFlightCardUpperBoundMinor",
    "fullFlightCreditCoverageMinor",
    "fullFlightMinor",
    "fundingDays",
    "initialWindowCount",
    "nextExpiryAt",
    "status",
    "windows"
  ],
  "additionalProperties": false
});
