// biome-ignore lint/performance/noBarrelFile: Public package entrypoint for `@dynamoi/mcp`.
export {
	buildProtectedResourceMetadata,
	buildWwwAuthenticateHeader,
	DYNAMOI_MCP_SCOPES,
} from "./auth/protected-resource";
export { verifyAccessToken } from "./auth/verify-token";
export type { Phase3Adapter } from "./server/create-server";
export { createDynamoiMcpServer } from "./server/create-server";
export {
	DynamoiCreateSmartLinkFromSpotifyInputSchema,
	DynamoiGetSmartLinkAnalyticsInputSchema,
	DynamoiGetSmartLinkArtistSettingsInputSchema,
	DynamoiGetSmartLinkInputSchema,
	DynamoiListSmartLinksInputSchema,
	DynamoiPublishSmartLinkInputSchema,
	DynamoiUpdateSmartLinkArtistSettingsInputSchema,
	DynamoiUpdateSmartLinkInputSchema,
	PHASE_4_TOOL_DEFINITIONS,
} from "./server/smart-link-tools";
export {
	DateRangeSchema,
	DynamoiGetArtistAnalyticsInputSchema,
	DynamoiGetArtistInputSchema,
	DynamoiGetBillingInputSchema,
	DynamoiGetCampaignAnalyticsInputSchema,
	DynamoiGetCampaignInputSchema,
	DynamoiGetCurrentUserInputSchema,
	DynamoiGetPlatformStatusInputSchema,
	DynamoiLaunchCampaignInputSchema,
	DynamoiListArtistsInputSchema,
	DynamoiListCampaignsInputSchema,
	DynamoiListMediaAssetsInputSchema,
	DynamoiPauseCampaignInputSchema,
	DynamoiResumeCampaignInputSchema,
	DynamoiSearchInputSchema,
	DynamoiUpdateBudgetInputSchema,
	PHASE_1_TOOL_DEFINITIONS,
	PHASE_2_TOOL_DEFINITIONS,
	PHASE_3_TOOL_DEFINITIONS,
	ToolFormatSchema,
} from "./server/tools";
export { handleMcpHttpRequest } from "./transport/http";
export type {
	AccessRole,
	ArtistTier,
	BillingStatus,
	CampaignDisplayStatus,
	CampaignType,
	CreateSmartLinkFromSpotifyData,
	GetArtistAnalyticsJsonData,
	GetArtistAnalyticsSummaryData,
	GetArtistData,
	GetArtistSummaryData,
	GetBillingData,
	GetBillingSummaryData,
	GetCampaignAnalyticsJsonData,
	GetCampaignAnalyticsSummaryData,
	GetCampaignData,
	GetCampaignSummaryData,
	GetCurrentUserData,
	GetCurrentUserSummaryData,
	GetPlatformStatusData,
	GetPlatformStatusSummaryData,
	GetSmartLinkAnalyticsData,
	GetSmartLinkAnalyticsSummaryData,
	GetSmartLinkData,
	GetSmartLinkSummaryData,
	LaunchCampaignData,
	ListArtistsData,
	ListArtistsSummaryData,
	ListCampaignsJsonData,
	ListCampaignsSummaryData,
	ListMediaAssetsData,
	ListMediaAssetsSummaryData,
	ListSmartLinksData,
	ListSmartLinksSummaryData,
	MediaAssetSummary,
	MoneyDisplay,
	PauseResumeCampaignData,
	PauseResumePlatformResult,
	PublishSmartLinkData,
	ResultEnvelope,
	SearchData,
	SearchResultType,
	SearchSummaryData,
	SmartLinkSettingsData,
	SmartLinkSummary,
	UpdateBudgetData,
	UpdateSmartLinkArtistSettingsData,
	UpdateSmartLinkData,
} from "./types";
